name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get secret 
      env:
        NUGETKEY: ${{ secrets.NUGETKEY }}
      run: |
        echo $NUGETKEY
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test /Nuages.Web.Tests/Nuages.Web.Tests.csproj --no-build --verbosity normal
    - name: Pack
      run: dotnet pack /Nuages.Web/Nuages.Web.csproj -c RELEASE
    - name: Push
      run: dotnet nuget push $OUTPUT/Nuages.Web.nupkg -k $NUGETKEY -s https://api.nuget.org/v3/index.json
      
   
