name: .NET

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c RELEASE
    - name: Test
      run: dotnet test Nuages.Web.Tests/Nuages.Web.Tests.csproj 
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack Nuages.Web/Nuages.Web.csproj --output ./nupkgs /p:Version=${VERSION}
    - name: Push
      run: dotnet nuget push ./nupkgs/*.nupkg -k ${{ secrets.NUGETKEY }} -s nuget.org
      
   
